apiVersion: v1
kind: Template
metadata:
  name: blueocean-jenkins
  annotations:
    description: "Selenium Node with Google Chrome browser"
    iconClass: "icon-selenium"
    tags: "selenium,node,chrome"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: blueocean-jenkins
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: blueocean
      type: Git
      git:
        uri: https://github.com/maddinenisri/openshift-jenkins-setup
        ref: master
    strategy:
      type: Docker
      DockerStrategy: {}
    output:
      to:
        kind: ImageStreamTag
        name: blueocean-jenkins:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: blueocean-jenkins
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest