apiVersion: v1
kind: Template
metadata:
  name: blueocean-jenkins
  annotations:
    description: "Blueocean Jenkins Template"
    iconClass: "icon-blueocean"
    tags: "jenkins,blueocean"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: blueocean-jenkins
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: blueocean
      type: Git
      git:
        uri: https://github.com/maddinenisri/openshift-jenkins-setup
        ref: master
    strategy:
      type: Docker
      DockerStrategy: {}
    output:
      to:
        kind: ImageStreamTag
        name: blueocean-jenkins:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: blueocean-jenkins
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: blueocean-jenkins
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - blueocean-jenkins
        from:
          kind: ImageStreamTag
          name: blueocean-jenkins:latest
    - type: ConfigChange
    replicas: 1
    selector:
      name: blueocean-jenkins
    template:
      metadata:
        name: blueocean-jenkins
        labels:
          name: blueocean-jenkins
      spec:
        containers:
        - image: blueocean-jenkins
          imagePullPolicy: Always
          name: blueocean-jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: blueocean-jenkins-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: blueocean_jenkins
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - persistentVolumeClaim:
            claimName: blueocean_jenkins_pvc
          name: blueocean-jenkins-1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: blueocean_jenkins
- apiVersion: v1
  kind: RoleBinding
  groupNames: null
  metadata:
    name: blueocean_jenkins_hostaccess
  roleRef:
    name: hostaccess
  subjects:
    kind: ServiceAccount
    name: blueocean_jenkins 
- apiVersion: v1
  kind: PersistentVolumeClaim 
  metadata:
    name: blueocean_jenkins_pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi                          
- apiVersion: v1
  kind: Service
  metadata:
    name: blueocean-jenkins
  spec:
    selector:
      name: blueocean-jenkins
    type: ClusterIP
    ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: blueocean-jenkins-jnlp
  spec:
    selector:
      name: blueocean-jenkins
    type: ClusterIP
    ports:
    - name: jnlp-port
      port: 50000
      targetPort: 50000
      protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: blueocean-jenkins
  spec:
    port:
      targetPort: http-port
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: blueocean-jenkins
      weight: 100
    wildcardPolicy: None
parameters:
  - name: name
    description: name
    value: blueocean-jenkins
