apiVersion: v1
kind: Template
metadata:
  name: oc-docker
  annotations:
    description: "Jenkins agnet Template"
    iconClass: "icon-oc-docker"
    tags: "oc-docker,jenkins-slave"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: oc-docker
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: oc-docker
      type: Git
      git:
        uri: https://github.com/maddinenisri/openshift-jenkins-setup
        ref: master
    strategy:
      type: Docker
      DockerStrategy: {}
    output:
      to:
        kind: ImageStreamTag
        name: oc-docker:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: oc-docker
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
